### ISSUE TITLE
Dns query seems to often return no results!

### ISSUE THREAD

**Issue by amtbnagios** [faicker/greendns#3]
version: greendns   0.9.11 & Python 3.7.3 & os x 10.13.6

$ dig www.facebook.com @127.0.0.1 -p1053

; <<>> DiG 9.10.6 <<>> www.facebook.com @127.0.0.1 -p1053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14768
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
; PAD: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ("..................................")
;; QUESTION SECTION:
;www.facebook.com.		IN	A

;; ANSWER SECTION:
www.facebook.com.	435	IN	CNAME	star-mini.c10r.facebook.com.
star-mini.c10r.facebook.com. 435 IN	A	157.240.22.35

;; Query time: 27 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Thu Apr 25 10:37:15 CST 2019
;; MSG SIZE  rcvd: 128

$ dig www.facebook.com @127.0.0.1 -p1053

; <<>> DiG 9.10.6 <<>> www.facebook.com @127.0.0.1 -p1053
;; global options: +cmd
;; connection timed out; no servers could be reached

$ dig www.facebook.com @127.0.0.1 -p1053

; <<>> DiG 9.10.6 <<>> www.facebook.com @127.0.0.1 -p1053
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by faicker** [comment]
So sorry.
Please use version 0.9.12.
