### ISSUE TITLE
改用GREENDNS做ROS的上游服务器后在ROS的缓存里出现很多NEGATIVE的记录

### ISSUE THREAD

**Issue by hleungg** [faicker/greendns#4]
改用GREENDNS做ROS的上游服务器后在ROS的缓存里出现很多NEGATIVE的记录。。。

[图片](https://ibb.co/807vrYN)

**Comment by faicker** [comment]
greendns配置是怎么样的

**Comment by hleungg** [comment]
[配置图片](https://ibb.co/rtQjmzf)

**Comment by faicker** [comment]
这个是正常的吧。这些域名直接从公共dns去dig返回就是NXDOMAIN。
